cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('create-checkout-session/<int:item_id>/', views.create_checkout_session, name='create_checkout_session'),  # путь к оплате товара
    path('success_pay/', views.success_pay, name='success_pay'),       # путь успешной оплаты  
    path('create_all_checkout_session/<str:item_ids>/', views.create_all_checkout_session, name='create_all_checkout_session'), # путь оплаты корзины
    path('delate_order/<int:order_id>/', views.delete_order, name='delete_order'),
]

shop/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('userauth.urls', namespace='userauth')),
    path('', include('main.urls', namespace='main')),
    
]

# Отдача static и media в режиме DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  
 
    
# Всегда отдавать media вручную — если не DEBUG и Render не справляется
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

userauth/urls.py
from django.urls import path
from .import views

app_name = 'userauth'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('cab/', views.user_cab, name='cab'),
    path('logout/', views.user_logout, name = 'logout'),
    path('edit/', views.user_edit, name = 'edit'),
    path('change_pass/', views.change_pass, name = 'change_pass'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Product

# Create your models here.

class Order(models.Model):       # модель заказа (покупки)
    STATUS_CHOICES = [
        ('pending', 'Ожидает оплаты'),
        ('paid', 'Оплачен'),
        ('failed', 'Ошибка оплаты'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)           # дата создания заказа
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')     # статус заказа
    paid = models.BooleanField(default=False)                # статус оплаты
    
    def __str__(self):
        return f"Заказ № {self.id} от {self.user.username}"
    
    def get_total_cost(self):                                          # общая сумма покупки
        return sum(item.get_cost() for item in self.items.all())
    
    
class OrderItem(models.Model):     # модель позиции (товаров) одного заказа
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def get_cost(self):
        return self.price * self.quantity
    
    
    
    
    

userauth/models.py
from django.db import models

# Create your models here.

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):    # <- форма создания юзера
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "form-input"}))
    email = forms.EmailField(required=True, label="Email", widget=forms.EmailInput(attrs={"class": "form-input"}))
    password1 = forms.CharField(required=True, label="Пароль", widget=forms.PasswordInput(attrs={"class": "form-input"}))
    password2 = forms.CharField(required=True, label="Повторите пароль", widget=forms.PasswordInput(attrs={"class": "form-input"}))
    
    class Meta:
        model = User   # <- модель наследуется от базового класса User от Django
        fields = ["username", "email", "password1", "password2"]
        
    def save(self, commit=True): # <- функция сохраняет пользователя в бд
        user = super(NewUserForm, self).save(commit=False)
        # ↑ False позволяет сначала модифицировать объект, а затем сохранить его, избегая промежуточного сохранения в базу
        user.email = self.cleaned_data.get("email")  # Используем get(), чтобы избежать ошибки KeyError, если email по какой-то причине отсутствует
        if commit:
            user.save()
        return user
        
class UsernameUpdateForm(forms.ModelForm):    # <- форма изменения username
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "forms-input"}))
    
    class Meta:
        model = User
        fields = ["username"]
        
class EmailUpdateForm(forms.ModelForm):     # <- форма изменения почты
    email = forms.EmailField(required=True, label="Email", widget=forms.EmailInput(attrs={"class": "forms-input"}))
        
    class Meta:
        model = User
        fields = ["email"]
        
    def clean_email(self):
        email = self.cleaned_data.get("email")
        # ↓ выполняет проверку уникальности email, исключая текущего пользователя
        if User.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError("Этот email уже испольузется!")
        return email
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
    
            

userauth/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from cart.models import *
# Create your views here.

def user_register(request):                      # <- функция регистрации юзера
    if request.method == "POST":
        register_form = NewUserForm(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            messages.success(request, "Вы успешно зарегистированы!")
            return redirect('main:home_page')
        else:
            messages.error(request, "Ошибка при регистрации!")
    register_form = NewUserForm()
    return render(request=request, template_name='userauth/register.html', context={'register_form': register_form,
                                                                                    'show_navbar': False,})
    
def user_login(request):         # <- функция входа юзера
    if request.method == "POST":
        login_form = AuthenticationForm(request, data=request.POST)     #  <- базовая форма Django для аутентификации
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)  # <- authenticate проверяет на наличие такого юзера в бд
            if user is not None:
                login(request, user)
                messages.success(request, f"Вы вошли как {username}")
                return redirect('main:home_page')
        else:
            messages.error(request, "Неправильный username или пароль!")
    login_form = AuthenticationForm()
    return render(request=request, template_name='userauth/login.html', context={'login_form': login_form,
                                                                                 'show_navbar': False,})
    
def user_logout(request):   # <- функция выхода юзера
    logout(request)
    return redirect('main:home_page')
     
def user_cab(request):  # функция личного кабинета юзера
    if request.user.is_authenticated:
        cart = Cart(request)   # получаем корзину из сессии
        cart_items = list(cart)   # нужно привести к списку
        orders = Order.objects.filter(user=request.user).order_by('created')
        username = request.user.username
        email = request.user.email
        return render(request, 'userauth/cab.html', {'cart_items': cart_items,
                                                    'cart_total': cart.get_total_price(),
                                                    'orders': orders})
    return redirect('userauth:login')  # если не авторизован
    
@login_required         # <- доступ к редактированию возможен только для авторизованных пользователей.
def user_edit(request):   # функция для изменения данных
    user = request.user # <- получаем текущего пользователя
    if request.method == "POST":
        if 'update_username' in request.POST:
            username_form = UsernameUpdateForm(request.POST, instance=user)  # передаем текущего пользователя
            email_form = EmailUpdateForm(instance=user)   # Не заполняем email-form, чтобы избежать ошибок
            if username_form.is_valid():
                username_form.save()
                return redirect('userauth:cab')
            
        elif 'update_email' in request.POST:
            email_form = EmailUpdateForm(request.POST, instance=user)
            username_form = UsernameUpdateForm(instance=user)  # Не трогаем username-form
            if email_form.is_valid():
                email_form.save()
                return redirect('userauth:cab')
            
    else:
        username_form = UsernameUpdateForm()  # Загружаем текущие данные
        email_form = EmailUpdateForm()  # Загружаем текущие данные
    return render(request=request, template_name='userauth/edit.html', context={'username_form': username_form,
                                                                                'email_form': email_form})
            
@login_required
def change_pass(request):    # функция для изменения пароля
    if request.method == "POST":
        pass_form = PasswordChangeForm(user=request.user, data=request.POST)
        if pass_form.is_valid():
            user = pass_form.save()  # Сохраняем новый пароль
            update_session_auth_hash(request, user)
            messages.success(request, "Пароль успешно изменён!")
    else:
        pass_form =  PasswordChangeForm(user=request.user)
        messages.error(request, "Повторите попытку")
    return render(request=request, template_name='userauth/change_pass.html', context={'pass_form': pass_form})
        
        
     
 
                

                
            
            
    

userauth/templates/userauth/cab.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
<title>Личный кабинет</title>
{% endblock %}

{% block content %}

<h3 style="margin-bottom: 20px; text-align: center;">Личный кабинет</h3>

<main>
{% if request.user.is_authenticated %}
<div style="width: 70%; margin: 0 auto;">
<table style="width: 100%; border-collapse: collapse;">
    <tr>
        <td style="border: 5px solid #ddd; padding: 10px;">Никнейм</td>
        <td style="border: 5px solid #ddd; padding: 10px;">{{ user.username }}</td>
    </tr>
    <tr>
        <td style="border: 5px solid #ddd; padding: 10px;">Почта</td>
        <td style="border: 5px solid #ddd; padding: 10px;">{{ user.email }}</td>
    </tr>
</table>        

<h4 style="margin-top: 40px; text-align: center;">Товары в корзине</h4>
{% if cart_items %}
<table style="border-collapse: collapse; width: 100%;">
    <tr>
        <td style="border: 3px solid #ddd; padding: 8px;">Название</td>
        <td style="border: 3px solid #ddd; padding: 8px;">Цена</td>
        <td style="border: 3px solid #ddd; padding: 8px;">Количество</td>
        <td style="border: 3px solid #ddd; padding: 8px;">Итого</td>        
    </tr>
    {% for item in cart_items %}
    <tr>
        {% load humanize %}
        <td style="border: 3px solid #ddd; padding: 8px;">{{ item.product.name }}</td>
        <td style="border: 3px solid #ddd; padding: 8px;">{{ item.price|intcomma }} ₸</td>
        <td style="border: 3px solid #ddd; padding: 8px;">{{ item.cart_quantity }}</td>
        <td style="border: 3px solid #ddd; padding: 8px;">{{ item.total_price|intcomma }} ₸</td>
    </tr>
    {% endfor %}
</table>
<br>
<table style="border-collapse: collapse; width: 100%; text-align: center;">
    <td style="border: 3px solid #ddd; padding: 8px;">Общая сумма корзины</td>  
    <td style="border: 3px solid #ddd; padding: 8px;">{{ cart_total|intcomma }} ₸</td> 
</table>
</div>
{% else %}
    <p>Корзина пуста</p>
{% endif %}
{% endif %}

<h4 style="margin-top: 40px; text-align: center;">Ваши покупки</h4>
{% if orders %}
    {% for order in orders %}
    <table style="border-collapse: collapse; width: 100%; margin-bottom: 30px; border: 2px solid #ccc;">
    <thead style="background-color: #f5f5f5;">
        <tr>
        <th colspan="3" style="padding: 10px; text-align: left; font-size: 18px;">
            Заказ от {{ order.created|date:"d.m.Y" }}
        </th>
        <tr>
            <th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">Товар</th>
            <th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">Количество</th>
            <th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">Цена</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{{ item.product.name }}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{{ item.quantity }}</td>
            {% load humanize %}
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{{ item.price|intcomma }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="2" style="padding: 10px; text-align: right; font-weight: bold;">Общая сумма:</td>
            <td style="padding: 10px; text-align: right; font-weight: bold;">{{ order.get_total_cost|intcomma }} ₸</td>
        </tr>
        <tr>
            <td colspan="2" style="padding: 10px; text-align: right; font-weight: bold;">Статус заказа:</td>
            <td style="padding: 10px; text-align: right; font-weight: bold;">{{ order.get_status_display }}</td>
        </tr>
        <tr>
            <td colspan="3" style="padding: 10px; text-align: right;">
            <form action="{% url 'cart:delete_order' order.id %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <button type="submit" style="
                background-color: #dc3545;
                color: white;
                border: none;
                padding: 8px 16px;
                font-size: 14px;
                border-radius: 4px;
                cursor: pointer;
                transition: 0.3s;
                "
                onmouseover="this.style.backgroundColor='#c82333'"
                onmouseout="this.style.backgroundColor='#dc3545'"
            >Удалить заказ
            </button>
            </form>
            </td>
        </tr>
    </tbody>
    </table>
    {% endfor %}
{% else %}
    <p style="text-align: center;">Нет завершенных покупок</p>
{% endif %}

<div class="extra-links" style="text-align: center; margin-top: 30px;">
<a href="{% url 'cart:cart_detail' %}">Перейти в корзину</a>
<a href="{% url 'userauth:edit' %}" style="margin-top: 25px;">Изменить данные</a>
</div>

</main>

{% endblock %}

userauth/templates/userauth/change_pass.html
{% extends "main/base.html" %}
{% load static %}

{% block title%}
<title>Изменение пароля</title>
{% endblock %}

{% block content %}

<main>
<form method="POST" class="form-container">
    <h3 style="margin-bottom: 20px;">Изменение пароля</h3>
    {% csrf_token %}
    <div class="form-group">
    <label for="{{ pass_form.old_password.id_for_label }}">{{ pass_form.old_password.label }}</label>
    {{ pass_form.old_password}}
    </div>

    <div class="form-group">
    <label for="{{ pass_form.new_password1.id_for_label }}">{{ pass_form.new_password1.label }}</label>
    {{ pass_form.new_password1}}
    </div>

    <div class="form-group">
    <label for="{{ pass_form.new_password2.id_for_label }}">{{ pass_form.new_password2.label }}</label>
    {{ pass_form.new_password2}}
    </div>

    <button type="submit" class="centered-button">Изменить пароль</button>

    <div class="extra-links">
        <a href="{% url 'userauth:cab' %}">Вернуться в личный кабинет</a>
    </div>
</form>
</main>

{% endblock %}

userauth/templates/userauth/edit.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

<main>

<div class="edit-wrapper">
<form method="POST" novalidate class="edit-container">
    <h3 style="margin-bottom: 20px; text-align: center;">Редактирование данных</h3>
    {% csrf_token %}
    <div class="edit-group">
    <label for="{{ username_form.id_for_label }}">{{ username_form.label }}</label>
    {{ username_form }}
    </div>

    <div class="button-wrapper">
    <button type="submit" name="update_username" class="centered-button">Обновить username</button>
    </div>
</form>

<form method="POST" novalidate class="edit-container">
    {% csrf_token %}
    <div class="edit-group">
    <label for="{{ email_form.id_for_label }}">{{ email_form.label }}</label>
    {{ email_form }}
    </div>

    <div class="button-wrapper">
    <button type="submit" name="update_email" class="centered-button">Обновить почту</button>
    </div>
</form>

    <div class="extra-links">
    <a href="{% url 'userauth:change_pass' %}">Изменить пароль</a>
    <a href="{% url 'userauth:cab' %}">Вернуться в личный кабинет</a>
    </div>
</div>
</main>

{% endblock %} 

userauth/templates/userauth/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
<title>Вход</title>
{% endblock %}

{% block content %}

<main>

<form method="POST" class="form-container">
    <h3 style="margin-bottom: 20px;">Войти</h3>
    {% csrf_token %}

    <div class="form-group">
    <label for="{{ login_form.username.id_for_label }}">{{ login_form.username.label }}</label>
    {{ login_form.username }}
    </div>

    <div class="form-group">
    <label for="{{ login_form.password.id_for_label }}">{{ login_form.password.label }}</label>
    {{ login_form.password }}
    </div>
    
    <div class="button-wrapper">
    <button type="submit" class="centered-button">Войти</button> 
    </div>

    <p>У вас нет аккаунта? Тогда зарегистрируйтесь<p>
    <a style="text-decoration: none; color: #008080;" href="{% url 'userauth:register' %}">
       <p style="margin-top: 2px; font-size: 20px;">Регистрация</p>
    </a>
  
</form>
</main>

{% endblock %}

userauth/templates/userauth/register.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
<title>Регистрация</title>
{% endblock %}

{% block content %}

<main>
<form method="POST" class="form-container">
    <h3 style="margin-bottom: 20px;">Регистрация</h3>
    {% csrf_token %}
    <div class="form-group">
        <label form="{{ register.form.username.id_for_label }}">{{ register_form.username.label }}</label>
        {{ register_form.username }}
    </div>
    <div class="form-group">
        <label form="{{ register.form.email.id_for_label }}">{{ register_form.email.label }}</label>
        {{ register_form.email }}
    </div>
    <div class="form-group">
        <label form="{{ register.form.password1.id_for_label }}">{{ register_form.password1.label }}</label>
        {{ register_form.password1 }}
    </div>
    <div class="form-group">
        <label form="{{ register.form.password2.id_for_label }}">{{ register_form.password2.label }}</label>
        {{ register_form.password2 }}
    </div>

    <div class="button-wrapper">
    <button type="submit" class="centered-button">Зарегистрироваться</button>
    <div>
</form>
</main>


{% endblock %}