cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('create-checkout-session/<int:item_id>/', views.create_checkout_session, name='create_checkout_session'),  # путь к оплате товара
    path('success_pay/', views.success_pay, name='success_pay'),       # путь успешной оплаты  
    path('create_all_checkout_session/<str:item_ids>/', views.create_all_checkout_session, name='create_all_checkout_session'), # путь оплаты корзины
    path('delate_order/<int:order_id>/', views.delete_order, name='delete_order'),
]

shop/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('userauth.urls', namespace='userauth')),
    path('', include('main.urls', namespace='main')),
    
]

# Отдача static и media в режиме DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  
 
    
# Всегда отдавать media вручную — если не DEBUG и Render не справляется
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Product

# Create your models here.

class Order(models.Model):       # модель заказа (покупки)
    STATUS_CHOICES = [
        ('pending', 'Ожидает оплаты'),
        ('paid', 'Оплачен'),
        ('failed', 'Ошибка оплаты'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)           # дата создания заказа
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')     # статус заказа
    paid = models.BooleanField(default=False)                # статус оплаты
    
    def __str__(self):
        return f"Заказ № {self.id} от {self.user.username}"
    
    def get_total_cost(self):                                          # общая сумма покупки
        return sum(item.get_cost() for item in self.items.all())
    
    
class OrderItem(models.Model):     # модель позиции (товаров) одного заказа
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def get_cost(self):
        return self.price * self.quantity
    
    
    
    
    

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(0, 6)]

class CartAddForm(forms.Form):
    cart_quantity = forms.TypedChoiceField(choices = PRODUCT_QUANTITY_CHOICES, coerce=int, initial=1, label="Количество")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    
class CartAddOneForm(forms.Form):
    cart_quantity = forms.TypedChoiceField(initial=1, coerce=int, widget=forms.HiddenInput)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    
    

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .forms import *
from .cart import *
from .models import *
from main.models import Product
from django.contrib import messages
import stripe
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY   # api key Stripe

@require_POST
def cart_add(request, product_id):         # функция добавления товара/товаров в корзину
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    
    form = CartAddForm(request.POST)
    one_form = CartAddOneForm(request.POST)
    
    if form.is_valid():
        cd = form.cleaned_data
        if cd['cart_quantity'] == 0:
            cart.remove(product)
            messages.error(request, f"{product.name} удален из корзины")
            return redirect('cart:cart_detail')
        else:
            cart.add(product=product, cart_quantity=cd['cart_quantity'], update_quantity=cd['update'])
        messages.success(request, f"{product.name} добавлен в корзину")
    elif one_form.is_valid():
        cd = one_form.cleaned_data
        cart.add(product=product, cart_quantity=cd['cart_quantity'], update_quantity=cd['update']) 
        messages.success(request, f"{product.name} добавлен в корзину")          
    return redirect('cart:cart_detail')    
    
def cart_remove(request, product_id):   # функция удаления товара из корзины
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):         # функция отображения детали корзины
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddForm(initial={'cart_quantity': item['cart_quantity'], 'update': True})
    return render(request, 'cart/cart_detail.html', {'cart':cart,
                                                     'show_navbar': False,             # скрываем верхнее меню на этой странице
                                                     'stripe_public_key': settings.STRIPE_PUBLIC_KEY,})   

def cart_clear(request):        # функция очистки корзины
    cart = Cart(request)
    messages.success(request, "Корзина очищена!")
    cart.clear()
    return redirect('cart:cart_detail')     

# ↓ Вьюха оплаты

@login_required
def success_pay(request):
    cart = Cart(request)
    order = Order.objects.create(user=request.user, status='paid', paid=True)
    
    # 1. Если в корзине есть товары → обычная покупка
    if len(cart) > 0:
        for item in cart:
            OrderItem.objects.create(
                order=order,
                product=item['product'],
                price=item['price'],
                quantity=item['cart_quantity']
            )
        cart.clear()
        
    # 2. Если в сессии есть single_item → покупка одного товара    
    elif 'single_item' in request.session:
        data = request.session['single_item']
        product = Product.objects.get(id=data['product_id'])
        OrderItem.objects.create(
                order=order,
                product=product,
                price=data['price'],
                quantity=data['quantity']
                )
        del request.session['single_item']
    return render(request, 'cart/success_pay.html', {'order': order})

@csrf_exempt
def create_checkout_session(request, item_id):             # функция оплаты одного товара
    if request.method == "POST":
        item = get_object_or_404(Product, id=item_id)
        
         # Сохраняем товар в сессии
        request.session['single_item'] = {
            'product_id': item.id,
            'price': float(item.price),
            'quantity': 1
        }
        
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items = [{
                'price_data': {
                    'currency': 'kzt',
                    'product_data': {
                        'name': item.name,
                    },
                    'unit_amount': int(item.price * 100), # Stripe требует цену в тыийнах
                },
                'quantity': 1,
            }],
            mode = 'payment',
            success_url='https://marketplace-audioshop.onrender.com/cart/success_pay/',
            cancel_url='https://marketplace-audioshop.onrender.com/',
        )
        return JsonResponse({'id': session.id})
    
        
@csrf_exempt
def create_all_checkout_session(request, item_ids):         # функция оплаты итоговой суммы в корзине
    if request.method == "POST":
        cart = Cart(request)
        
        # ↓ Сначала проверим сумму
        total = sum(item['product'].price * item['cart_quantity'] for item in cart)
        if total > 999999.99:
            return JsonResponse(
                {'error': 'Сумма заказа превышает лимит (999,999.99 ₸). Удалите часть товаров и попробуйте снова.'},
                status=400
            )
            
         #  Преобразуем строку item_ids в список int
        ids = [int(i) for i in item_ids.split(",") if i.strip().isdigit()]
        items = Product.objects.filter(id__in=ids)
        
        line_items = []
        for item in cart:
            line_items.append({
                'price_data': {
                    'currency': 'kzt',
                    'unit_amount': int(item['product'].price * 100),
                    'product_data': {
                        'name': item['product'].name,
                    },
                },
                'quantity': item['cart_quantity'],
            })
            
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items = line_items,
            mode = 'payment',
            success_url='https://marketplace-audioshop.onrender.com/cart/success_pay/',
            cancel_url='https://marketplace-audioshop.onrender.com/',
        )
        return JsonResponse({'id': session.id})
   
@login_required
def delete_order(request, order_id):                 # удаление отдельного заказа
    order = get_object_or_404(Order, id=order_id, user=request.user)
    order.delete()
    return redirect('userauth:cab')
 

cart/templates/cart/cart_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<main>
<div>
    <h1 style="text-align: center;">Корзина</h1>
</div>

<div class="cart-detail">
    <div class="cart-container">
    {% for item in cart %}
    {% with product=item.product %}
        <div class="cart-item">
            <img src="/media/{{product.photo}}" height="220px" width = "280px" style="margin: 5px">
            <p>{{ product.name }}</p>
            {% load humanize %}
            <p>{{ product.price|intcomma }} &#8376;</p>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{ item.update_quantity_form.cart_quantity }}
            {{ item.update_quantity_form.update }}
            <input type="submit" value ="Изменить количество" style="background-color: lightgreen; color: black;">
            <p><strong>{{ item.total_price|intcomma }} &#8376;</strong></p>
            </form>
        </div>
    {% endwith %}
    {% endfor %}
    </div>
</div>
<div class="cart-total">
    <small><strong>Итого {{ cart.get_total_price|intcomma }} &#8376;</strong></small>
    <div class="pay-clear">
        <button id="checkout-all-button" class="pay-all" style="width: 200px">Оплатить</button>
        <form action="{% url 'cart:cart_clear' %}" method="POST">
            {% csrf_token %}
        <button class="clear-cart" style="width: 200px">Очистить корзину</button>
        </form>
    </div>
</div>
<!-- Модальное окно -->
<div id="errorModal" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="close-button">&times;</span>
        <p id="modal-error-text"></p>
    </div>
<div>
<script>
    var stripe = Stripe('{{ stripe_public_key }}');
    const itemIdsString = "{% for item in cart %}{{ item.product.id }}{% if not forloop.last %}, {% endif %}{% endfor %}";
    const modal = document.getElementById("errorModal");
    const modalText = document.getElementById("modal-error-text");
    const closeBtn = document.querySelector(".close-button");

    document.getElementById("checkout-all-button").addEventListener('click', function () {
      const itemIds = itemIdsString;
      fetch(`/cart/create_all_checkout_session/${itemIds}/`, {
          method: "POST",
          headers: {
              "X-CSRFToken": "{{ csrf_token }}",
              "Content-type": "application/json"
          },
      })
      .then(response => {
        if (!response.ok) {
            return response.json().then(data => {
                throw new Error(data.error || "Неизвестная ошибка!");
            });
        }
        return response.json();
      })
      .then(session => {
        if (!session.id) {
            throw new Error("Ошибка: не удалось сделать оплату");
        }
        return stripe.redirectToCheckout({sessionId: session.id});
      })
      .catch(error => {
          modalText.textContent = error.message;
          modal.style.display = 'block';
      });
  });
  
  // Закрытие по кнопке "×"
  closeBtn.onclick = function () {
    modal.style.display = "none";
  }

   // Закрытие при клике вне окна

   window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
   }
  </script>
</main>
{% endblock %}

cart/templates/cart/success_pay.html
{%extends 'main/base.html'%}
{% load static %}
 
{% block title %}
<title>Success payment</title>
{% endblock %}

{% block content %}
<main>
  <h2 style="text-align: center; color: darkgreen;">Оплата прошла успешно!</h2>
  <p style="text-align: center;">Ваш заказ был успешно оплачен. Подтверждение отправлено на вашу почту.</p>
</main>
{% endblock %}