cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('create-checkout-session/<int:item_id>/', views.create_checkout_session, name='create_checkout_session'),  # путь к оплате товара
    path('success_pay/', views.success_pay, name='success_pay'),       # путь успешной оплаты  
    path('create_all_checkout_session/<str:item_ids>/', views.create_all_checkout_session, name='create_all_checkout_session'), # путь оплаты корзины
    path('delate_order/<int:order_id>/', views.delete_order, name='delete_order'),
]

main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path('', views.all_products, name='home_page'),
    path('<int:item_id>/', views.product_detail, name='product_detail'),
    path('contacts/', views.contact_view, name='contacts'),
]

shop/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('userauth.urls', namespace='userauth')),
    path('', include('main.urls', namespace='main')),
    
]

# Отдача static и media в режиме DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  
 
    
# Всегда отдавать media вручную — если не DEBUG и Render не справляется
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

userauth/urls.py
from django.urls import path
from .import views

app_name = 'userauth'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('cab/', views.user_cab, name='cab'),
    path('logout/', views.user_logout, name = 'logout'),
    path('edit/', views.user_edit, name = 'edit'),
    path('change_pass/', views.change_pass, name = 'change_pass'),
]

main/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Product(models.Model):
    name = models.CharField(verbose_name="Название товара", max_length=100, unique=True)
    price = models.PositiveIntegerField(verbose_name="Цена товара")
    maker = models.ForeignKey("Maker", on_delete=models.PROTECT, verbose_name="Производитель", null=True, blank=True)
    description = models.TextField(verbose_name="Описание товара", default="")
    category = models.ForeignKey("Category", on_delete=models.PROTECT, verbose_name="Категория", null=True, blank=True)
    color = models.CharField(verbose_name="Цвет товара", max_length=50, null=True, blank=True)
    quantity = models.PositiveIntegerField(verbose_name="Количество товара", default=0)
    photo = models.ImageField(verbose_name="Фото товара", upload_to="photo/%Y/%m/%d", null=True, blank=True)
    full_description = RichTextField(verbose_name="Полное описание товара", default="")
    
    def __str__(self):
        return f"{self.name} - {self.price} тенге - {self.category}"
      
    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(fields=["name", "maker", "category", "color"], name="unique_product")
        ]
        
class Category(models.Model):
    name = models.CharField(verbose_name="Название категории", max_length=60)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"] 
        
   
class Maker(models.Model):
    name = models.CharField(verbose_name="Название производителя", max_length=60, unique=True)
    country = models.CharField(verbose_name="Страна производителя", max_length=100)
    
    def __str__(self):
        return f"{self.name} - {self.country}"
    
    class Meta:
        verbose_name = "Производитель"
        verbose_name_plural = "Производители"
        ordering = ["name"]
        constraints = [                  
            models.UniqueConstraint(fields=["name", "country"], name="unique_maker")
        ]
        
        
class InStock(models.Model):
    product = models.OneToOneField("Product", on_delete=models.CASCADE, related_name="stock", verbose_name="Товар") # Связываем с Product
    quantity = models.PositiveIntegerField(verbose_name="Количество товара", default=0)
    
    def __str__(self):
        return f"{self.product.name} - {self.quantity} шт."
    
    class Meta:
        verbose_name = "Склад"
        verbose_name_plural = "Склады"
        
    
    

main/forms.py
from django import forms
from .models import Maker

class BrandFilterForm(forms.Form):
    brand = forms.ModelMultipleChoiceField(
        queryset = Maker.objects.all(),
        required = False,
        widget = forms.CheckboxSelectMultiple
    )

main/views.py
from django.shortcuts import get_object_or_404, render
from .models import *
from .forms import *
from django.core.paginator import Paginator
from cart.forms import *
from django.db.models.functions import Lower
import stripe
from django.conf import settings


# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY     # api key Stripe

def all_products(request):             # вьюха главной страницы
    items = Product.objects.all()
    brand_form = BrandFilterForm(request.GET)        # Форма для фильтрации (GET-параметры)
    selected_brands = request.GET.getlist("brand")
    cart_one_form = CartAddOneForm()
    price_range = request.GET.get("price_range")
    category_id = request.GET.get("category")
    color = request.GET.get("color")
    country = request.GET.get("country")
    search_all = request.GET.get("search_all")
    categories = Category.objects.all()
    makers = Maker.objects.all()
     
    if brand_form.is_valid() and brand_form.cleaned_data['brand']:           # фильтрация по брендам
        items = items.filter(maker__in=brand_form.cleaned_data['brand'])
        
    if price_range == "1":                          # фильтрация по ценам
        items = items.filter(price__lte=300000)
        
    if price_range == "2":
        items = items.filter(price__gte=300001, price__lte=600000)
        
    if price_range == "3":
        items = items.filter(price__gte=600001)
    
    if category_id:                                   # фильтрация по категориям
        items = items.filter(category_id=category_id)
        
    if color:                                        # фильтрация по цветам
        items = items.filter(color=color)
        
    if country:                                     # фильтрация по странам
        maker = makers.filter(country=country)
        items = items.filter(maker__in=maker)
        
    if search_all:                          # поиск в каталоге по названию
        items = items.filter(name__icontains=search_all)
        
    raw_colors = (Product.objects.exclude(color__isnull=True)   #  Получаем цвета, приводим к нижнему регистру, фильтруем, чистим
                  .exclude(color__exact='')
                  .values_list('color', flat=True))
    
    colors = sorted(set(color.strip() for color in raw_colors))  # Убираем дубликаты с учётом регистра и лишних пробелов
    
    raw_countries = (Maker.objects.exclude(country__exact='')
                    .values_list('country', flat=True))
    
    countries = sorted(set(country.strip() for country in raw_countries))
    
    paginator = Paginator(items, 20)  # 20 товаров на странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'main/home_page.html', {'items': page_obj,
                                                   'brand_form': brand_form, 
                                                   'selected_brands': selected_brands,
                                                   'cart_one_form': cart_one_form,
                                                   'page_obj': page_obj,
                                                   'color': color,
                                                   'category_id': category_id,
                                                   'country': country,
                                                   'countries': countries,
                                                   'categories': categories,
                                                   'colors': colors,
                                                   'search-all': search_all,
                                                   'show_navbar': True, })
                                                

def product_detail(request, item_id):         # вьюха деталей продуктов
    item = Product.objects.get(id = item_id)
    cart_one_form = CartAddOneForm()
     
    return render(request, 'main/product_detail.html', {'item': item,
                                                        'cart_one_form': cart_one_form,
                                                        'stripe_public_key': settings.STRIPE_PUBLIC_KEY,
                                                        'show_navbar': False,})

def contact_view(request):
    return render(request, 'main/contacts.html')
    

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title%} {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
    {% if messages %}
    <div id="custom-messages" style="position: fixed; top: 20px; right: 20px; z-index: 1000;">
        {% for message in messages %}
        <div class="custom-alert custom-alert-{{ message.tags }}">
            <span class="custom-icon">{% if message.tags == "success" %}✔{% elif message.tags == "error" %}✖{% else %}ℹ{% endif %}</span>
            <span>{{ message }}</span>
            <span class="custom-close" onclick="this.parentElement.remove()">✕</span>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <header class="header">
        <div class="header-main">
            <div class="logo">
                <a href="{% url 'main:home_page' %}">
                    <h1>Audio Shop</h1>
                </a>
            </div>
            {% if show_navbar%}
            <nav class="nav-menu">
                <div class="dropdown">
                    <a href="#">Категории</a>
                    <div class="dropdown-content">
                        {% for category in categories %}
                        <a href="{% url 'main:home_page' %}?category={{ category.id }}">{{ category.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="dropdown">
                    <a href="#">Цвета</a>
                    <div class="dropdown-content">
                        {% for color in colors %}
                        {% if color %}
                        <a href="{% url 'main:home_page' %}?color={{ color}}">{{ color }}</a>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="dropdown">
                    <a href="#">Страны</a>
                    <div class="dropdown-content">
                        {% for country in countries %}
                        <a href="{% url 'main:home_page' %}?country={{ country|urlencode }}">{{ country}}</a>
                        {% endfor %}
                    </div>
                </div>
                {% else %}
                <div class="back-home" style="margin-left: 60%;">
                    <a href="{% url 'main:home_page' %}" style="text-decoration: none; font-size: 18px; color:#008080;">Вернуться на главную</a>
                </div>
                {% endif %}
            </nav>
            <div class="header-actions">
                <form id="searchForm" method="GET" action="{% url 'main:home_page' %}">
                <input type="text" name="search_all" placeholder="Поиск по каталогу" class="search-bar" id="searchInput">
                </form>
                <div class="icons" >
                    <a href="{% url 'cart:cart_detail' %}">
                        <img src="{% static 'icons/free-icon.png' %}" class="icon" style="width:28px; height:28px; margin-right:20px; color: white;">
                    </a>
                    {% if request.user.is_authenticated %}
                    <div class="dropdown">
                        <img src="{% static 'icons/icons8-cab.png' %}" class="icon" style="width:28px; height:28px; margin-right:20px; color: white;
                        cursor: pointer;">
                        <div class="dropdown-cab-menu">
                            <a href="{% url 'userauth:cab' %}">Личный кабинет</a>
                            <a href="{% url 'userauth:logout' %}">Выйти</a>
                        </div>
                    </div>
                    {% else %}
                    <a href="{% url 'userauth:login' %}">
                        <img src="{% static 'icons/icons8-48.png' %}" class="icon" style="width:30px; height:30px;">
                    </a>     
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="{% static 'js/script.js' %}"></script>
    {% block content %} 
    {% endblock%}
    <footer>
        <p>&copy; 2025 Мой Сайт</p>
        <a href="{% url 'main:contacts' %}">Контакты</a>
    </footer>
  
    <script>
        setTimeout(() => {
          const messages = document.getElementById('custom-messages');
          if (messages) messages.remove();
        }, 3500); // через 3.5 сек исчезает
      </script>
</body>
    
</html>

main/templates/main/contacts.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
<title>Контакты</title>
{% endblock %}

{% block content %}
<main>

<style>
.contacts-view {
    background-color: #f0f0f0;
    padding: 30px 20px;
    font-family: 'Inter', sans-serif;
    color: #1a1a1a;
    font-size: 16px;
    line-height: 1.6;
    text-align: left;
}
        
.contacts-view .icon {
    width: 32px;
    height: 32px;
    margin: 0 5px;
    vertical-align: middle;
    transition: transform 0.2s;
}
        
.contacts-view .icon:hover {
    transform: scale(1.1);
}
        
.contacts-view a {
    text-decoration: none;
}</style>

<div class="contacts-view">
    <p style="text-align: center;">Со мной можно связаться по этим контактам
        <a href="https://wa.me/77018938933" target="_blank">
        <img src="{% static 'icons/icons8-whatsapp.png' %}" alt="WhatsApp" class="icon">
        </a>
        <a href="https://wa.me/77018938933" target="_blank">
        <img src="{% static 'icons/icons8-телеграм.png' %}" alt="Telegramm" class="icon">
        </a>
    </p>
</div>

</main>

{% endblock %}

main/templates/main/home_page.html
{% extends 'main/base.html' %}
{% load static %}

{% block title%}
<title>Главная страница</title>
{%  endblock %}

{% block content%}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>
<main>
<div class="all-page">
    <div class="sidebar">
        <form method="get" class="filter-form">
            <h3>Цена<h3>
                <div class="price-list">
                    <label class="price-item">
                    <input type="checkbox" name="price_range" value="1" {% if request.GET.get.price_range == "1" %}checked{% endif %}>
                    0 &#8376; - 300 000 &#8376;
                    </label>
                    <label class="price-item">
                    <input type="checkbox" name="price_range" value="2" {% if request.GET.get.price_range == "2" %}checked{% endif %}>
                    300 001 &#8376; - 600 000 &#8376;
                    </label>
                    <label class="price-item">
                    <input type="checkbox" name="price_range" value="3" {% if request.GET.get.price_range == "3" %}checked{% endif %}>
                    600 001 &#8376; - 999 999 &#8376;
                    </label>                   
                </div>
                <button type="submit">Выбрать</button>
            <h3>Бренд</h3>
                <div class="brand-list">
                    <div id="brand-wrapper">
                        {% for brand in brand_form.fields.brand.queryset %}
                        <label class="brand-item {% if forloop.counter > 10 %}hidden-brand{% endif %}">
                        <input type="checkbox" name="brand" value="{{ brand.id}}"
                        {% if brand.id|stringformat:"s" in selected_brands %}checked{% endif %}>
                        {{ brand.name }}
                        </label> 
                    {% endfor %}
                    </div>
                {% if brand_form.fields.brand.queryset|length > 10 %}
                <a href="#" id="toggle-brands">Все бренды</a>
                {% endif %}
                </div>
                <button type="submit">Выбрать</button>
            </form>
        </div>
    <div class="content-area">
        <div class="product-container">
        {% for item in items %}
            <div class="product-card">
                <div class="product-top">
                    <div class="product-image hover-wrapper">
                    {% if item.photo %}
                    <img src="{{ item.photo.url }}" alt="{{ item.name }}">
                    {% else %}
                    <img src="{% static 'img/istockphoto.jpg' %}" alt="Нет фото">
                    {% endif %}
                    <a href="{% url 'main:product_detail' item.id %}" class="hover-overlay">
                        <span><i class="fas fa-eye"></i>Подробнее</span>
                    </a>
                </div>
                <div class="product-info">
                    <p class="product-name" title="{{ item.name }}">{{ item.name }}</p>
                    <p style="font-family: Candara, serif; max-height: 2.4em; min-height: 2.4em;">{{ item.description }}</p>
                    {% load humanize %}
                    <p style="font-family: fangsong;">{{ item.price|intcomma }} &#8376;</p>
                    <p class="stock-status">
                        {% if item.quantity > 0 %}
                        <i class="fas fa-check-circle" style="color: green;"></i> В наличии
                        {% else %}
                        <i class="fas fa-times-circle" style="color: red;"></i> Нет в наличии
                        {% endif %}
                    </p>
                </div>
            </div>
            <div class="product-bottom">
                <form action="{% url 'cart:cart_add' item.id %}" method="POST">
                    {{ cart_one_form }}
                    {% csrf_token %}
                <button class="add-to-cart">В корзину</button>
                </form>
            </div>
        </div>
{% endfor %}
<div class="page-filler"></div>  <!-- заполнитель -->
    <!-- Пагинация -->
{% if page_obj.has_other_pages %}
    {% with request.GET.urlencode|cut:"page="|add:"&" as query %}
      
        <div class="pagination">
            <ul class="pagination-list">
            {% if page_obj.has_previous %}
            <li>
                <a href="?{{ query }}page={{ page_obj.previous_page_number }}">←</a>
            </li>
            {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == 1 or num == page_obj.paginator.num_pages or num >= page_obj.number|add:-2 and num <= page_obj.number|add:2 %}
                {% if page_obj.number == num %}
                    <li><span class="current-page">{{ num }}</span></li>
                {% else %}
                    <li>
                        <a href="?{{ query }}page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}

            {% elif num == page_obj.number|add:-3 or num == page_obj.number|add:3 %}
                <li><span>...</span></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li><a href="?{{ query }}page={{ page_obj.next_page_number }}">ДАЛЕЕ →</a>
            </li>
        {% endif %}
        </ul>
    </div>
    {% endwith %}
    {% endif %}
    </div>
</div>
</main>
</body>

{% endblock %}

main/templates/main/product_detail.html
{%extends 'main/base.html'%}
{% load static %}

{% block title %}
        <title>Страница товара</title>
{% endblock %}

{%block content%}

<main class="product-detail">
  <!-- Левая часть -->
  <div style="width:60%;">
      <img src="{{item.photo.url}}" style="height:550px;">
  </div>
  <!-- Средняя часть -->
   <!-- 🧾 Блок 1: Основная информация -->
  <div class="product-detail-info" style="width:80%;">
      <h2 style="text-align:center;">Характеристики</h2>
      <div class="spec-row">
        <span class="spec-name">Категория</span>
        <span class="spec-value">{{ item.category }}</span>
      </div>
      <div class="spec-row">
        <span class="spec-name">Производитель</span>
        <span class="spec-value">{{ item.maker.name }} | {{ item.maker.country }}</span>
      </div>
      <div class="spec-row">
        <span class="spec-name">Цвет</span>
        <span class="spec-value" style="margin-bottom: 30px;">{{ item.color }}</span>
      </div>
      <h2 style="text-align:center;">Описание</h2>
      <div class="spec-row">
        <span class="full-description">{{ item.full_description|safe }}</span>
      </div>
  </div>
  <!-- Правая часть -->
  <div class="product-buy" style="width:40%">
    <h2>{{ item.name }}</h2>
    <hr>
    <div class="product-price">
      {% load humanize %}
      {{ item.price|intcomma }} ₸
    </div>
      <button id="checkout-button" class="buy-btn">Купить</button>
      <form action="{% url 'cart:cart_add' item.id %}" method="POST">
            {{ cart_one_form }}
            {% csrf_token %}
      <button type="submit" class="cart-btn">В корзину</button>
      </form>
  </div>
  <script>
    var stripe = Stripe('{{ stripe_public_key }}');
    document.getElementById("checkout-button").addEventListener('click', function () {
      fetch("{% url 'cart:create_checkout_session' item.id %}", {
          method: "POST",
          headers: {
              "X-CSRFToken": "{{ csrf_token }}",
              "Content-type": "application/json"
          },
      })
      .then(function (response) {
          return response.json();
      })
      .then(function (session) {
          return stripe.redirectToCheckout({sessionId: session.id});
      })
      .catch(function (error) {
          console.error("Ошибка: ", error);
      });
  });
  </script>
</main>

{%endblock%}